version: '3'
services:
  nginx:
    image: nginx:1.28-alpine
    ports:
      - 8081:80
    volumes:
      - /Users/ilya/Documents/Java/file-uploader/frontend/html:/usr/share/nginx/html:ro
  back:
    image: tiny-storage:1.0
    build:
      context: . # не забыть сбилдить проект перед сборкой. На будущее сделать сборку докера двухфазной
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
     - 8082:8080
    volumes:
      - /Users/ilya/Documents/Java/file-uploader/src/main/docker/jvm_temp:/storage
